CREATE SCHEMA IF NOT EXISTS testActor AUTHORIZATION SA;
USE `testActor` ;

DROP TABLE IF EXISTS actor;

CREATE TABLE actor (
  actor_id INTEGER PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  last_update TIMESTAMP NOT NULL,
);
